### ISSUE TITLE
Flutter_svg 2.0+

### ISSUE THREAD

**Issue by Aggie85** [mhmzdev/awesome_snackbar_content#10]
Howdy!

First, thanks for a great widget set!

Any chance of updating dependency to flutter_svg 2.0+ soon?

All the best,

Aggie85

**Comment by manuelduarte077** [comment]
```
Resolving dependencies...
Because wallpaper_app depends on awesome_snackbar_content ^0.1.0 which depends on flutter_svg ^1.0.3, flutter_svg ^1.0.3 is required.
So, because wallpaper_app depends on flutter_svg ^2.0.0+1, version solving failed.
pub finished with exit code 1
```
there are problems with the flutter_svg package

**Comment by mhmzdev** [comment]
Hey!
Will be doing that soon but not JUST NOW, because I'm working with a lot of projects that are still on previous versions of flutter.

So, I will need to upgrade my SDK to latest one that sometimes causes crashes on previous projects.
Would love if you can just do that for me and create a PR. I'll definitely merge the code!

Much love!

**Comment by JohnF17** [comment]
Hello @mhmzdev, Kindly review my PR, it seems to be a good solution. 🙂

**Comment by okandemirofficial** [comment]
Hello, we kindly waiting merge the PR @mhmzdev 🙂

**Comment by mhmzdev** [comment]
PR has been merged with version issue, publishing new version on pub.dev
